module.exports = [            
  'node_modules/@polymer/polymer/*.js',
  'node_modules/codemirror/**/*.js',
  'node_modules/coffeelint/lib/coffeelint.js',
  'node_modules/jshint/dist/jshint.js',
  'node_modules/font-awesome/**/*.woff',
  'node_modules/font-awesome/**/*.ttf',
  'node_modules/font-awesome/**/*.svg',
  'node_modules/hammerjs/hammer.min.js',
  'node_modules/hammerjs/hammer.min.js.map',
  'node_modules/klayjs/klay.js',
  'node_modules/klayjs-noflo/klay-noflo.js',
  'node_modules/react/dist/react-with-addons.min.js',
  'node_modules/react-dom/dist/react-dom.min.js',
  'node_modules/observe-js/src/observe.js',
  'node_modules/@webcomponents/webcomponentsjs/webcomponents-lite.js',
];
