import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'tsdown';
import info from './package-lock.json' with { type: 'json' };

const { packages } = info;
const here = dirname(fileURLToPath(import.meta.url));

/**
 * Vendor builds, per SPEC "Build/Vendoring Mechanics": the bundler is used
 * strictly to flatten and export external dependencies into single ES module
 * files inside `vendor/`, so the live application itself runs natively via
 * import maps and native ESM — no build step for first-party code.
 *
 * Vendor file names are unversioned so first-party imports and import maps
 * stay stable across dependency bumps; `git diff` on rebuilds shows what a
 * bump changed.
 *
 * Type declarations are generated, not hand-written: JS bundles are built
 * from the packages' own entry points, and type-only builds re-export each
 * package through a first-party entry file (utils/*-entry.js) so the vendor
 * type surface is generated from the package's shipped declarations. Build
 * outputs are kept between runs (`clean: false`) so the generated
 * declarations and sibling builds are not wiped.
 */
const vendor = {
  platform: 'browser',
  format: 'esm',
  outDir: 'vendor',
  clean: false,
};

export default defineConfig([
  {
    entry: {
      noflo: 'node_modules/noflo/src/lib/NoFlo.js',
    },
    ...vendor,
    // Inline all dependencies: import maps map only this one file
    noExternal: [/./],
    alias: {
      'node:events': resolve(here, './src/shims/event-emitter.js'),
      events: resolve(here, './src/shims/event-emitter.js'),
      // fbp-graph requires fs for journal file persistence, never used in the
      // browser
      fs: resolve(here, './src/worker/empty-fs.js'),
      'node:fs': resolve(here, './src/worker/empty-fs.js'),
    },
    // The `require`/`fs` shims must stay the first statements: fbp-graph's
    // journal persistence is stubbed out. Types flow from the package's own
    // shipped declarations through the type-only build below (work document
    // #24) — no @ts-nocheck banner.
    banner: {
      js: `var require = () => ({}); var fs = {};`,
    },
    comments: true,
    copy: [
      {
        from: 'node_modules/source-code-pro/WOFF2/OTF/SourceCodePro-Regular.otf.woff2',
        to: 'vendor/webfonts',
        rename: `sourcecodepro-${packages['node_modules/source-code-pro'].version}.woff2`,
      },
    ],
  },
  {
    entry: {
      // The browser surface: SVG rendering only — the invite QR codes are
      // SVG strings injected into Shadow DOM (no canvas)
      qrcode: 'node_modules/qrcode/lib/browser.js',
    },
    ...vendor,
    // Inline all dependencies (dijkstrajs et al.)
    noExternal: [/./],
  },
  {
    entry: {
      yjs: 'node_modules/yjs/dist/yjs.mjs',
    },
    ...vendor,
    // Inline lib0 and other transitive dependencies
    noExternal: [/./],
  },
  {
    entry: {
      'y-indexeddb': 'node_modules/y-indexeddb/src/y-indexeddb.js',
    },
    ...vendor,
    // yjs stays external: all contexts must share ONE Yjs instance, served as
    // the sibling vendor/yjs.js bundle
    external: ['yjs'],
    outputOptions: {
      paths: {
        yjs: './yjs.js',
      },
    },
  },
  {
    // Browser-safe @reticulum/core surface plus the WebSocket interface,
    // bundled as one module so all contexts share one core instance
    // (see utils/reticulum-entry.js). Types are generated by the type-only
    // build at the bottom of this file.
    entry: {
      'reticulum-core': './utils/reticulum-entry.js',
    },
    ...vendor,
    // @reticulum/core is dependency-free by design; inline everything
    noExternal: [/./],
    // One file: the vendor contract is a single module per package, and
    // relative chunks would complicate the worker's import graph
    splitting: false,
    // @reticulum/core reads the global `crypto` directly; the banner
    // shadows it with the X25519-polyfilling shim so browsers without
    // native X25519 (WebKit) can run the full stack
    banner: {
      js: 'import crypto from "../src/shims/crypto-subtle.js";',
    },
  },
  {
    entry: {
      'y-reticulum': 'node_modules/y-reticulum/src/index.js',
    },
    ...vendor,
    // yjs and @reticulum/core stay external: all contexts must share one
    // instance of each, served as sibling vendor bundles. lib0 and
    // y-protocols are inlined. The bzip2 WASM dependency is stubbed out —
    // y-reticulum falls back to uncompressed Resources when it is missing
    external: ['yjs', '@reticulum/core'],
    alias: {
      '@digitaldefiance/bzip2-wasm': resolve(here, './src/shims/bzip2-stub.js'),
    },
    // Types flow from y-reticulum's shipped declarations through the
    // type-only build below (work document #24): 0.4.0 emits declarations
    // for every chunk of its build — no @ts-nocheck banner.
    splitting: false,
    outputOptions: {
      paths: {
        yjs: './yjs.js',
        '@reticulum/core': './reticulum-core.js',
      },
    },
  },
  {
    // @reticulum/dacar pure core plus the §11 direct-link Delta push
    // transport (utils/dacar-entry.js): external to the shared sibling
    // @reticulum/core bundle, same contract as y-reticulum
    entry: {
      dacar: './utils/dacar-entry.js',
    },
    ...vendor,
    external: ['@reticulum/core'],
    // The dacar package itself is inlined (it ships no declarations, so a
    // bare-specifier re-export would be invisible to the type checker);
    // only @reticulum/core stays external. Declarations are generated
    // locally from the package's JSDoc sources by
    // utils/generate-vendor-types.js (work document #24) — no
    // @ts-nocheck banner.
    noExternal: [/^@reticulum\/dacar/],
    splitting: false,
    outputOptions: {
      paths: {
        '@reticulum/core': './reticulum-core.js',
      },
    },
  },
  {
    entry: {
      'fontawesome-icons': './utils/icon-map.js',
    },
    dts: true,
    ...vendor,
    copy: [
      {
        from: 'node_modules/@fortawesome/fontawesome-free/webfonts/fa-solid-900.woff2',
        to: 'vendor/webfonts',
        rename: `fontawesome-${packages['node_modules/@fortawesome/fontawesome-free'].version}.woff2`,
      },
    ],
  },
  {
    entry: {
      jedison: './node_modules/jedison/dist/esm/jedison.js',
    },
    ...vendor,
    outputOptions: {
      banner: '// @ts-nocheck',
    },
  },
  {
    // @noble/curves (ed25519 module, includes X25519): first-party fallback
    // crypto for the X25519 polyfill; @noble/hashes is inlined (zero-dep
    // chain, MIT)
    entry: {
      'noble-curves': './utils/noble-curves-entry.js',
    },
    ...vendor,
    noExternal: [/./],
    splitting: false,
  },
  {
    // Type-only builds (see utils/*-entry.js): packages that ship their own
    // declarations re-export through first-party entries, generating the
    // vendor type surface from those declarations
    entry: {
      yjs: './utils/yjs-entry.js',
      'y-indexeddb': './utils/y-indexeddb-entry.js',
      'reticulum-core': './utils/reticulum-core-types-entry.js',
      'noble-curves': './utils/noble-curves-entry.js',
      'y-reticulum': './utils/y-reticulum-types-entry.js',
    },
    dts: { emitDtsOnly: true },
    ...vendor,
  },
]);
