/**
 * @file Vendor builds (SPEC "Build/Vendoring Mechanics"): the bundler is
 * used strictly to flatten and export external dependencies into single ES
 * module files inside `vendor/`, so the live application itself runs
 * natively via import maps and native ESM — no build step for first-party
 * code. Run this only when a dependency is added or updated: vendor outputs
 * are committed, and `git diff` on rebuilds shows what a bump changed.
 *
 * The bundler is esbuild. The vendor contract it implements:
 *
 * - Vendor file names are unversioned so first-party imports and import
 *   maps stay stable across dependency bumps.
 * - One module per package: packages that must share one instance across
 *   contexts (yjs, @reticulum/core) are never inlined into their consumers;
 *   the sibling-external plugin below keeps them external and rewrites
 *   their specifiers to the relative sibling paths (`./yjs.js`,
 *   `./reticulum-core.js`) the import maps resolve.
 * - Everything else is inlined: import maps cannot resolve nested bare
 *   specifiers inside third-party modules.
 * - Banner-injected code is prepended to the output verbatim: the noflo
 *   `require`/`fs` stubs must stay the first statements (fbp-graph's
 *   journal persistence is stubbed out), and the reticulum-core crypto
 *   import shadows the global so browsers without native X25519 (WebKit)
 *   can run the full stack.
 *
 * Type declarations are generated, not hand-written — see
 * utils/generate-vendor-types.js.
 */

import { copyFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";
import info from "../package-lock.json" with { type: "json" };

const { packages } = info;
const here = dirname(fileURLToPath(import.meta.url));

/**
 * Default options shared by all vendor builds.
 *
 * @type {esbuild.BuildOptions}
 */
const vendor = {
  bundle: true,
  platform: "browser",
  format: "esm",
  outdir: resolve(here, "../vendor"),
  logLevel: "info",
};

/**
 * Escapes a package name for literal use in an esbuild onResolve filter.
 *
 * @param {string} name
 * @returns {string}
 */
function escapeFilter(name) {
  return name.replace(/[\\^$.|?*+()[{]/g, "\\$&");
}

/**
 * Marks sibling vendor bundles external and rewrites their specifiers to
 * relative sibling paths. esbuild emits the path returned by `onResolve`
 * verbatim for external modules, which reproduces the specifier rewriting
 * the previous bundler did with its output `paths` option: consumers of the
 * vendored module must all receive the same shared instance, served as the
 * sibling vendor bundle. Subpath imports of an external package (the lxmf
 * stamper deep-imports `@reticulum/core/src/utils/stamper.js`) rewrite to
 * the sibling too — it re-exports the same surface.
 *
 * @param {Record<string, string>} siblings Package name to sibling path.
 * @returns {esbuild.Plugin}
 */
function siblingExternals(siblings) {
  const filter = new RegExp(
    `^(?:${Object.keys(siblings).map(escapeFilter).join("|")})(?:/.*)?$`,
  );
  return {
    name: "vendor-siblings",
    setup(build) {
      build.onResolve({ filter }, (args) => {
        const segments = args.path.split("/");
        const name = segments[0].startsWith("@")
          ? segments.slice(0, 2).join("/")
          : segments[0];
        return { path: siblings[name], external: true };
      });
    },
  };
}

const yjsSibling = { yjs: "./yjs.js" };
const coreSibling = { "@reticulum/core": "./reticulum-core.js" };
const yjsAndCoreSiblings = { ...yjsSibling, ...coreSibling };

/**
 * The runtime vendor builds. Type declarations for these packages are
 * generated by utils/generate-vendor-types.js, not here.
 *
 * @type {esbuild.BuildOptions[]}
 */
const builds = [
  {
    entryPoints: {
      noflo: resolve(here, "../node_modules/noflo/src/lib/NoFlo.js"),
    },
    ...vendor,
    alias: {
      "node:events": resolve(here, "../src/shims/event-emitter.js"),
      events: resolve(here, "../src/shims/event-emitter.js"),
      // fbp-graph requires fs for journal file persistence, never used in
      // the browser
      fs: resolve(here, "../src/worker/empty-fs.js"),
      "node:fs": resolve(here, "../src/worker/empty-fs.js"),
    },
    banner: {
      js: "var require = () => ({}); var fs = {};",
    },
  },
  {
    // The browser surface: SVG rendering only — the invite QR codes are SVG
    // strings injected into Shadow DOM (no canvas)
    entryPoints: {
      qrcode: resolve(here, "../node_modules/qrcode/lib/browser.js"),
    },
    ...vendor,
  },
  {
    entryPoints: { yjs: resolve(here, "../node_modules/yjs/dist/yjs.mjs") },
    ...vendor,
  },
  {
    entryPoints: {
      "y-indexeddb": resolve(
        here,
        "../node_modules/y-indexeddb/src/y-indexeddb.js",
      ),
    },
    ...vendor,
    plugins: [siblingExternals(yjsSibling)],
  },
  {
    // Browser-safe @reticulum/core surface plus the WebSocket interface,
    // bundled as one module so all contexts share one core instance (see
    // utils/reticulum-entry.js)
    entryPoints: {
      "reticulum-core": resolve(here, "./reticulum-entry.js"),
    },
    ...vendor,
    banner: {
      js: 'import crypto from "../src/shims/crypto-subtle.js";',
    },
  },
  {
    entryPoints: {
      "y-reticulum": resolve(here, "../node_modules/y-reticulum/src/index.js"),
    },
    ...vendor,
    plugins: [siblingExternals(yjsAndCoreSiblings)],
    alias: {
      // The bzip2 WASM dependency is stubbed out — y-reticulum falls back
      // to uncompressed Resources when it is missing
      "@digitaldefiance/bzip2-wasm": resolve(
        here,
        "../src/shims/bzip2-stub.js",
      ),
    },
  },
  {
    // @reticulum/dacar pure core plus the §11 direct-link Delta push
    // transport (utils/dacar-entry.js): external to the shared sibling
    // @reticulum/core bundle, same contract as y-reticulum
    entryPoints: { dacar: resolve(here, "./dacar-entry.js") },
    ...vendor,
    plugins: [siblingExternals(coreSibling)],
  },
  {
    // @reticulum/lxmf: external to the shared sibling @reticulum/core
    // bundle, same contract as y-reticulum and dacar — one core instance
    // per process (the split-brain warning must never fire)
    entryPoints: { lxmf: resolve(here, "./lxmf-entry.js") },
    ...vendor,
    plugins: [siblingExternals(coreSibling)],
  },
  {
    entryPoints: {
      "fontawesome-icons": resolve(here, "./icon-map.js"),
    },
    ...vendor,
  },
  {
    entryPoints: {
      jedison: resolve(here, "../node_modules/jedison/dist/esm/jedison.js"),
    },
    ...vendor,
    banner: {
      js: "// @ts-nocheck",
    },
  },
  {
    // @noble/curves (ed25519 module, includes X25519): first-party fallback
    // crypto for the X25519 polyfill; @noble/hashes is inlined (zero-dep
    // chain, MIT)
    entryPoints: {
      "noble-curves": resolve(here, "./noble-curves-entry.js"),
    },
    ...vendor,
  },
];

for (const build of builds) {
  await esbuild.build(build);
}

// Versioned webfont copies: the fonts are the one vendor artifact whose
// file names carry versions (they are referenced from CSS, not import maps)
const webfonts = resolve(here, "../vendor/webfonts");
mkdirSync(webfonts, { recursive: true });
copyFileSync(
  resolve(
    here,
    "../node_modules/source-code-pro/WOFF2/OTF/SourceCodePro-Regular.otf.woff2",
  ),
  resolve(
    webfonts,
    `sourcecodepro-${packages["node_modules/source-code-pro"].version}.woff2`,
  ),
);
copyFileSync(
  resolve(
    here,
    "../node_modules/@fortawesome/fontawesome-free/webfonts/fa-solid-900.woff2",
  ),
  resolve(
    webfonts,
    `fontawesome-${packages["node_modules/@fortawesome/fontawesome-free"].version}.woff2`,
  ),
);
