name: Node CI

on: [push]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2.3.3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm run build
        npm test
      env:
        CI: true
  merge-me:
    name: Auto-merge dependency updates
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: ridedott/merge-me-action@v1.8.15
      with:
        GITHUB_LOGIN: 'dependabot[bot]'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
